drop table tb_user if exists;
create table tb_user (
    id bigint generated by default as identity ,
    username varchar(40) not null ,
    name varchar(20),
    age int,
    balance decimal,
    primary key (id)
);